## Implement Adam Optimization Algorithm
Implement the Adam (Adaptive Moment Estimation) optimization algorithm in Python. Adam is an optimization algorithm that adapts the learning rate for each parameter. Your task is to write a function adam_optimizer that updates the parameters of a given function using the Adam algorithm.

The function should take the following parameters:

    f: The objective function to be optimized
    grad: A function that computes the gradient of f
    x0: Initial parameter values
    learning_rate: The step size (default: 0.001)
    beta1: Exponential decay rate for the first moment estimates (default: 0.9)
    beta2: Exponential decay rate for the second moment estimates (default: 0.999)
    epsilon: A small constant for numerical stability (default: 1e-8)
    num_iterations: Number of iterations to run the optimizer (default: 1000)
    
The function should return the optimized parameters.

In [12]:
import numpy as np

def objective_function(x):
    return x[0]**2 + x[1]**2

def gradient(x):
    return np.array([2*x[0], 2*x[1]])

x0 = np.array([1.0, 1.0])


In [11]:
learning_rate=0.001
beta1=0.9
beta2=0.999
epsilon=1e-8
num_iterations=10

In [7]:
for i in range(num_iterations):
	mt = (beta1 * objective_function(x0)) + (1 - beta1) * gradient(x0)
	##RMSprop
	vt = (beta2 * objective_function(x0)) + (1 - beta2) * gradient(x0)**2
	##bias correction
	mhat_t = mt/(1 - beta1**i)
	vhat_t = vt/(1 - beta2**i)

	#update
	x0 -= learning_rate * (mhat_t / (np.sqrt(vhat_t) + epsilon))
x0

array([nan, nan])

In [13]:
np.array(x0, dtype=float)

array([1., 1.])

In [15]:
np.zeros_like(x0)

array([0., 0.])

In [14]:
x0

array([1., 1.])

In [18]:
def adam_optimizer(f, grad, x0, learning_rate=0.001, beta1=0.9, beta2=0.999,
                   epsilon=1e-8, num_iterations=10):
    # x = np.array(x0, dtype=float)          # copy, ensure float
	m = np.zeros_like(x0)                   # 1st moment
	v = np.zeros_like(x0)                   # 2nd moment

	for t in range(1, num_iterations + 1):
		g = grad(x0)

		# Update biased first and second moment estimates
		m = beta1 * m + (1 - beta1) * g
		v = beta2 * v + (1 - beta2) * (g ** 2)

		# Bias correction
		m_hat = m / (1 - beta1 ** t)
		v_hat = v / (1 - beta2 ** t)

		# Parameter update
		x0 -= learning_rate * m_hat / (np.sqrt(v_hat) + epsilon)
	return x0

In [19]:
x_opt = adam_optimizer(objective_function, gradient, x0)

print("Optimized parameters:", x_opt)

Optimized parameters: [0.99000325 0.99000325]
