## Linear Regression Using Gradient Descent

Write a Python function that performs linear regression using gradient descent. The function should take NumPy arrays X (features with a column of ones for the intercept) and y (target) as input, along with learning rate alpha and the number of iterations, and return the coefficients of the linear regression model as a NumPy array. Round your answer to four decimal places. -0.0 is a valid result for rounding a very small number.

In [92]:
import numpy as np
X = np.array([[1, 1], [1, 2], [1, 3]])
y = np.array([1, 2, 3])
alpha = 0.01
iterations = 1000

In [93]:
m, n = X.shape
y = y.reshape(-1, 1) 	# Make sure y is a column vector
theta = np.zeros((n, 1))

In [72]:
Y_pred = X @ theta
Y_pred

array([[0.],
       [0.],
       [0.]])

In [94]:
for i in range(iterations):
    Y_pred = X @ theta
    error = Y_pred - y
    gradient = (1/m) * X.T @ error
    theta -= alpha * gradient
print(theta)

[[0.11071521]
 [0.95129619]]


In [41]:
theta

array([[0.],
       [0.]])

In [ ]:
def linear_regression_gradient_descent(X: np.ndarray, y: np.ndarray, alpha: float, iterations: int) -> np.ndarray:
	"""
	Perform linear regression using gradient descent.

	m = number of training examples
	n = number of parameters (features), technically n-1 features, 1st column is for intercept

	X: shape (m, n), `m` training examples with `n` input values for each feature
	y: shape (m, 1) array with the target values (ground truth)
	alpha: learning rate
	iterations: number of gradient descent steps
	"""

	m, n = X.shape
	y = y.reshape(-1, 1) 	# Make sure y is a column vector
	theta = np.zeros((n, 1))

	# TODO: Your code here

	return np.round(theta.flatten(), 4) 	# Rounded to 4 decimals